name: '[Workflow] On Dockerfile Change'

concurrency:
  group: push-${{ github.branch }}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ops/docker/**'
      - '.releaserc.json'
      - './github/workflows/on_dockerfile_change.yml'
jobs:
  release:
    name: 'Release'
    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main

  build:
    name: 'Build'
    needs: [ release ]
    if: always() && needs.release.result == 'success' && needs.release.outputs.version != ''
    uses: webgrip/workflows/.github/workflows/docker-build-and-push.yml@main
    with:
      docker-context: '.'
      docker-file: './ops/docker/mkdocs/Dockerfile'
      docker-tags: |
        ${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
        ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.release.outputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
