name: '[Workflow] On Dockerfile Change'

concurrency:
  group: push-${{ github.branch }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ops/docker/**'

jobs:
  determine-changed-dockerfiles:
    name: "Docker"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/docker'

  release:
    name: 'Release'
    if: >
      always()
      && needs.determine-changed-dockerfiles.outputs.changed-paths != '[]'
    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main

  build-and-push-changed-dockerfiles:
    name: "Deploy Changed Services"
    needs: [ determine-changed-dockerfiles, release ]
    if: >
      always()
      && needs.release.result == 'success'
      && needs.determine-changed-dockerfiles.outputs.changed-paths != '[]'
    uses: ./.github/workflows/build-and-push-docker-images.yml
    with:
      paths: ${{ needs.determine-changed-dockerfiles.outputs.changed-paths }}
      version: ${{ needs.release.outputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
