name: '[Workflow] On Dockerfile Change'

concurrency:
  group: push-${{ github.branch }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ops/docker/**'

jobs:
  release:
    name: 'Release'
    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main

  determine-changed-builder:
    name: "Docker"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/docker/010-builder'

  build-and-push-changed-builder:
    name: "Deploy Changed Services"
    needs: [ determine-changed-builder, release ]
    if: >
      always()
      && needs.release.result == 'success'
      && needs.determine-changed-builder.outputs.changed-paths != '[]'
    uses: ./.github/workflows/build-and-push-docker-images.yml
    with:
      paths: ${{ needs.determine-changed-builder.outputs.changed-paths }}
      version: ${{ needs.release.outputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  determine-changed-application:
    name: "Docker"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/docker/020-application'

  build-and-push-changed-application:
    name: "Deploy Changed Services"
    needs: [ determine-changed-application, release ]
    if: >
      always()
      && needs.release.result == 'success'
      && needs.determine-changed-application.outputs.changed-paths != '[]'
    uses: ./.github/workflows/build-and-push-docker-images.yml
    with:
      paths: ${{ needs.determine-changed-application.outputs.changed-paths }}
      version: ${{ needs.release.outputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
